### ISSUE TITLE
Memory leak in display_data / Tkinter conflict

### ISSUE THREAD

**Issue by SamuelLBau** [UCSD-E4E/radio_collar_tracker#20]
Branch: gui_initial
File: display_data.py

on line 99 (ctr + 'f' NATHANTODO) 
plot.close() closes tkinter windows. Commenting it out causes a memory leak. Need to close the plot without closing tkinter windows

**Comment by ntlhui** [comment]
Consider running display_data as a subprocess, not in the same thread.  That way matplotlib uses a differen tkinter instance.
